version: "3"
services:
  rin:
    build: .
    tty: true
    volumes:
      - ./app:/app
    command: "node app.js"
    networks:
      - br0
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - br0
    volumes:
      - ./mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

volumes:
  mongo:

networks:
  br0:
    driver: bridge
