version: "3"
services:
  bot:
    build: .
    tty: true
    volumes:
      - ./app:/app
    depends_on:
      - mongo
    ports:
      - "127.0.0.1:8080:8080"

  mongo:
    image: mongo
    volumes:
      - ./mongo/init.js:/docker-entrypoint-initdb.d/init.js:ro
      - ./mongo/db:/data/db
    environment:
      - MONGO_INITDB_DATABASE=admin
    command: [mongod, --auth]
